### ISSUE TITLE
Module stop working, No longer Weatherchart Displays MMM

### ISSUE THREAD

**Issue by SaschaSp** [paphko/mmm-weatherchart#5] opened 2017-07-19 14:56 UTC
Since 19.07.2017 approx 10:00 there is no longer Weatherchart displayed (it works for more then 7 months)in my MM. Restart dos Not change.

**Comment by keesem** [comment] 2017-07-20 21:06
Same problem here. I was testing it from March 2017, and I never had a problem. 
My Raspberry was down for a few days and now that I booted it, I see that Weatherchart is no longer working. it just displays an image logo instead of the chart. 
Please fix this, because the module is great.

**Comment by DaHarry** [comment] 2017-07-21 07:33
Same Problem, since 19.07.2017 it display only a little icon :-(
Restart doesn't change anything.

**Comment by murrayb8** [comment] 2017-07-22 09:22
I can confirm I am also having this this issue, strangely it appears that the source image meteogram.png on yr.no is still accessible so it is not clear why it is failing if nothing else has changed.

**Comment by paphko** [comment] 2017-07-22 20:14
I just checked the sources and it's clear why it doesn't work anymore: the image is now provided as an embedded svg, not as a png file any more.

The bad thing is that we must now extract the svg part from the entire html file - which means that new code must be written to do that.

The good thing is that we could do additional things, e.g.  modify its colors as we like.

**Comment by paphko** [comment] 2017-07-22 20:32
@murrayb8 you're right! the image still exists. But my strategy to use a timestamp query in the URL does not work any longer. I replaced that with an anchor which apparently does still work. However, I don't know whether browsers may then cache the image. Please try the latest master branch and report back whether or not updating the image still works.

**Comment by DaHarry** [comment] 2017-07-22 21:57
I pull the new version and it looks good now.  Thanks!

**Comment by DaHarry** [comment] 2017-07-24 08:33
Hi, the mmm-weatherchart doesn't update the Image. still the same since install and reboot.

**Comment by paphko** [comment] 2017-07-24 20:09
I though as much :-(

[Here](https://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url) is some discussion about this problem but the solutions are not applicable.

Although the image itself does work...
-> https://www.yr.no/place/Germany/North_Rhine-Westphalia/Duisburg/meteogram.png
...adding a query does not work any longer ('Bad request' is responded):
-> https://www.yr.no/place/Germany/North_Rhine-Westphalia/Duisburg/meteogram.png?x

I don't know how to add additional html header information as described in the [link above](https://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url).

There seems to be some parameter as described in [this comment](https://github.com/electron/electron/issues/1360#issuecomment-156506130), but it requires extending js/electron.js and I don't know (yet) whether this fixes the case. Moreover, I don't know whether there are side effects in other modules.

Any other ideas???

**Comment by paphko** [comment] 2017-07-25 18:42
We might have a [solution provided by spectroman](https://github.com/paphko/mmm-weatherchart/issues/1#issuecomment-317645819) 😄 
I'm currently testing it...

**Comment by paphko** [comment] 2017-07-26 07:51
Fixed with latest commit. Thank you spectroman!

**Closed by paphko** 2017-07-26 07:51 UTC
