### ISSUE TITLE
Picture broken 

### ISSUE THREAD

**Issue by amomat** [paphko/mmm-weatherchart#2] opened 2017-03-01 21:28 UTC
Hi

I have installed your module and it works fine when I have your example:

country: 'Germany',
            area: 'North_Rhine-Westphalia',
            city: 'Duisburg',

But when I want to see my city it shows as a broken picture. I live in Oslo Norway. The url is: http://www.yr.no/place/Norway/Oslo/Oslo/Oslo/

Or 

http://www.yr.no/place/Norway/Oslo/Oslo/Bestum/

for a closer location. Looks like there is another "option" for Norway to pinpoint more exactly. Or am I doing something wrong?

**Comment by paphko** [comment] 2017-03-02 12:40
Duplicate of https://github.com/paphko/mmm-weatherchart/issues/1

**Closed by paphko** 2017-03-02 12:40 UTC
